# Generated by Django 4.2 on 2023-08-01 07:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Driver_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plate_no', models.CharField(max_length=20)),
                ('Insuarance_start_date', models.DateField()),
                ('Insuarance_expiry_date', models.DateField()),
                ('Distane_remaining', models.IntegerField(default=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Start_odometer_reading', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Stop_odometer_reading', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('vehicle_condition', models.CharField(max_length=50)),
                ('initial_JMP', models.TimeField()),
                ('final_JMP', models.TimeField()),
                ('Driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_app.driver')),
                ('Vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_app.vehicle')),
            ],
        ),
    ]
