# Generated by Django 4.2.1 on 2023-08-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='cost_per_km',
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Plate_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
