# Generated by Django 4.2.1 on 2023-08-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='Round_trip_distance',
            field=models.IntegerField(default=0),
        ),
    ]
