# Generated by Django 4.2.1 on 2023-08-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0002_email_remove_fuel_cost_per_km_alter_driver_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='previous_odometer_reading',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='expected_efficiency',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
