# Generated by Django 4.2.1 on 2023-08-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0002_journey_round_trip_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='Overspeeding',
            field=models.IntegerField(),
        ),
    ]
