# Generated by Django 4.2.1 on 2023-08-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0003_remove_fuel_previous_odometer_reading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Distance_remaining',
            field=models.IntegerField(default=5000),
        ),
    ]
