# Generated by Django 4.2 on 2023-08-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0003_journey_destination_journey_passengers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='odometer',
            field=models.IntegerField(default=0),
        ),
    ]
