# Generated by Django 4.2 on 2023-08-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0004_vehicle_odometer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='Distane_remaining',
            new_name='Distance_remaining',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_inspection_date',
            field=models.DateField(default='Null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='next_inspection_date',
            field=models.DateField(default='Null'),
            preserve_default=False,
        ),
    ]
