# Generated by Django 4.2 on 2023-08-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0005_rename_distane_remaining_vehicle_distance_remaining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='last_inspection_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='next_inspection_date',
        ),
    ]
