# Generated by Django 4.2 on 2023-08-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0006_remove_vehicle_last_inspection_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_inspection_date',
            field=models.DateField(default='2023-02-14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='next_inspection_date',
            field=models.DateField(default='2023-02-14'),
            preserve_default=False,
        ),
    ]
