# Generated by Django 4.2 on 2023-08-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0007_vehicle_last_inspection_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_service_distance',
            field=models.IntegerField(default='2023-08-01'),
            preserve_default=False,
        ),
    ]
